all:
	xelatex rl-tutorial.tex
	xelatex rl-tutorial.tex

clean:
	rm -rf *.aux
	rm -rf *.toc
	rm -rf *.out
	rm -rf *.log
	rm -rf *.listing
	rm -rf *.bcf
	rm -rf *.xml
	rm -rf _minted/
	rm -rf *.nav
	rm -rf *.snm